package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * Acquirer generated by hbm2java
 */
public class Acquirer  implements java.io.Serializable {


     private Integer acquirerId;
     private String acquirerName;

    public Acquirer() {
    }

    public Acquirer(String acquirerName) {
       this.acquirerName = acquirerName;
    }
   
    public Integer getAcquirerId() {
        return this.acquirerId;
    }
    
    public void setAcquirerId(Integer acquirerId) {
        this.acquirerId = acquirerId;
    }
    public String getAcquirerName() {
        return this.acquirerName;
    }
    
    public void setAcquirerName(String acquirerName) {
        this.acquirerName = acquirerName;
    }




}


