package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * BatchClosure generated by hbm2java
 */
public class BatchClosure  implements java.io.Serializable {


     private String reservationNumber;
     private String creditCardNumber;
     private String transactionAuthCode;
     private String commerceId;
     private String batchNumber;
     private String acquirerId;

    public BatchClosure() {
    }

    public BatchClosure(String reservationNumber, String creditCardNumber, String transactionAuthCode, String commerceId, String batchNumber, String acquirerId) {
       this.reservationNumber = reservationNumber;
       this.creditCardNumber = creditCardNumber;
       this.transactionAuthCode = transactionAuthCode;
       this.commerceId = commerceId;
       this.batchNumber = batchNumber;
       this.acquirerId = acquirerId;
    }
   
    public String getReservationNumber() {
        return this.reservationNumber;
    }
    
    public void setReservationNumber(String reservationNumber) {
        this.reservationNumber = reservationNumber;
    }
    public String getCreditCardNumber() {
        return this.creditCardNumber;
    }
    
    public void setCreditCardNumber(String creditCardNumber) {
        this.creditCardNumber = creditCardNumber;
    }
    public String getTransactionAuthCode() {
        return this.transactionAuthCode;
    }
    
    public void setTransactionAuthCode(String transactionAuthCode) {
        this.transactionAuthCode = transactionAuthCode;
    }
    public String getCommerceId() {
        return this.commerceId;
    }
    
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId;
    }
    public String getBatchNumber() {
        return this.batchNumber;
    }
    
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }
    public String getAcquirerId() {
        return this.acquirerId;
    }
    
    public void setAcquirerId(String acquirerId) {
        this.acquirerId = acquirerId;
    }




}


