package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * Ccbrand generated by hbm2java
 */
public class Ccbrand  implements java.io.Serializable {


     private String code;
     private String name;
     private String acquirerName;
     private String acquirerId;

    public Ccbrand() {
    }

	
    public Ccbrand(String code, String acquirerName, String acquirerId) {
        this.code = code;
        this.acquirerName = acquirerName;
        this.acquirerId = acquirerId;
    }
    public Ccbrand(String code, String name, String acquirerName, String acquirerId) {
       this.code = code;
       this.name = name;
       this.acquirerName = acquirerName;
       this.acquirerId = acquirerId;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAcquirerName() {
        return this.acquirerName;
    }
    
    public void setAcquirerName(String acquirerName) {
        this.acquirerName = acquirerName;
    }
    public String getAcquirerId() {
        return this.acquirerId;
    }
    
    public void setAcquirerId(String acquirerId) {
        this.acquirerId = acquirerId;
    }




}


