package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * Channel generated by hbm2java
 */
public class Channel  implements java.io.Serializable {


     private char code;
     private String name;

    public Channel() {
    }

	
    public Channel(char code) {
        this.code = code;
    }
    public Channel(char code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public char getCode() {
        return this.code;
    }
    
    public void setCode(char code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


