package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private String isoCode;
     private String name;

    public Country() {
    }

	
    public Country(String isoCode) {
        this.isoCode = isoCode;
    }
    public Country(String isoCode, String name) {
       this.isoCode = isoCode;
       this.name = name;
    }
   
    public String getIsoCode() {
        return this.isoCode;
    }
    
    public void setIsoCode(String isoCode) {
        this.isoCode = isoCode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


