package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * Currency generated by hbm2java
 */
public class Currency  implements java.io.Serializable {


     private String isoCode;
     private String currencycol;

    public Currency() {
    }

	
    public Currency(String isoCode) {
        this.isoCode = isoCode;
    }
    public Currency(String isoCode, String currencycol) {
       this.isoCode = isoCode;
       this.currencycol = currencycol;
    }
   
    public String getIsoCode() {
        return this.isoCode;
    }
    
    public void setIsoCode(String isoCode) {
        this.isoCode = isoCode;
    }
    public String getCurrencycol() {
        return this.currencycol;
    }
    
    public void setCurrencycol(String currencycol) {
        this.currencycol = currencycol;
    }




}


