package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * Etickets generated by hbm2java
 */
public class Etickets  implements java.io.Serializable {


     private String reservationNumber;
     private String eticket;

    public Etickets() {
    }

    public Etickets(String reservationNumber, String eticket) {
       this.reservationNumber = reservationNumber;
       this.eticket = eticket;
    }
   
    public String getReservationNumber() {
        return this.reservationNumber;
    }
    
    public void setReservationNumber(String reservationNumber) {
        this.reservationNumber = reservationNumber;
    }
    public String getEticket() {
        return this.eticket;
    }
    
    public void setEticket(String eticket) {
        this.eticket = eticket;
    }




}


