package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * Pages generated by hbm2java
 */
public class Pages  implements java.io.Serializable {


     private String codRes;
     private String failure;
     private String sucess;

    public Pages() {
    }

    public Pages(String codRes, String failure, String sucess) {
       this.codRes = codRes;
       this.failure = failure;
       this.sucess = sucess;
    }
   
    public String getCodRes() {
        return this.codRes;
    }
    
    public void setCodRes(String codRes) {
        this.codRes = codRes;
    }
    public String getFailure() {
        return this.failure;
    }
    
    public void setFailure(String failure) {
        this.failure = failure;
    }
    public String getSucess() {
        return this.sucess;
    }
    
    public void setSucess(String sucess) {
        this.sucess = sucess;
    }




}


