package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Traceability generated by hbm2java
 */
public class Traceability  implements java.io.Serializable {


     private Integer id;
     private String reservationNumber;
     private String processStepCode;
     private Date date;
     private String transactionStatusCode;

    public Traceability() {
    }

    public Traceability(String reservationNumber, String processStepCode, Date date, String transactionStatusCode) {
       this.reservationNumber = reservationNumber;
       this.processStepCode = processStepCode;
       this.date = date;
       this.transactionStatusCode = transactionStatusCode;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getReservationNumber() {
        return this.reservationNumber;
    }
    
    public void setReservationNumber(String reservationNumber) {
        this.reservationNumber = reservationNumber;
    }
    public String getProcessStepCode() {
        return this.processStepCode;
    }
    
    public void setProcessStepCode(String processStepCode) {
        this.processStepCode = processStepCode;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getTransactionStatusCode() {
        return this.transactionStatusCode;
    }
    
    public void setTransactionStatusCode(String transactionStatusCode) {
        this.transactionStatusCode = transactionStatusCode;
    }




}


