package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * UserHasChannel generated by hbm2java
 */
public class UserHasChannel  implements java.io.Serializable {


     private UserHasChannelId id;

    public UserHasChannel() {
    }

    public UserHasChannel(UserHasChannelId id) {
       this.id = id;
    }
   
    public UserHasChannelId getId() {
        return this.id;
    }
    
    public void setId(UserHasChannelId id) {
        this.id = id;
    }




}


