package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * UserHasCcbrand generated by hbm2java
 */
public class UserHasCcbrand  implements java.io.Serializable {


     private UserHasCcbrandId id;

    public UserHasCcbrand() {
    }

    public UserHasCcbrand(UserHasCcbrandId id) {
       this.id = id;
    }
   
    public UserHasCcbrandId getId() {
        return this.id;
    }
    
    public void setId(UserHasCcbrandId id) {
        this.id = id;
    }




}


