package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * UserHasCountryId generated by hbm2java
 */
public class UserHasCountryId  implements java.io.Serializable {


     private int userId;
     private String isoCode;

    public UserHasCountryId() {
    }

    public UserHasCountryId(int userId, String isoCode) {
       this.userId = userId;
       this.isoCode = isoCode;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getIsoCode() {
        return this.isoCode;
    }
    
    public void setIsoCode(String isoCode) {
        this.isoCode = isoCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserHasCountryId) ) return false;
		 UserHasCountryId castOther = ( UserHasCountryId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getIsoCode()==castOther.getIsoCode()) || ( this.getIsoCode()!=null && castOther.getIsoCode()!=null && this.getIsoCode().equals(castOther.getIsoCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getIsoCode() == null ? 0 : this.getIsoCode().hashCode() );
         return result;
   }   


}


