package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * UserHasCountry generated by hbm2java
 */
public class UserHasCountry  implements java.io.Serializable {


     private UserHasCountryId id;

    public UserHasCountry() {
    }

    public UserHasCountry(UserHasCountryId id) {
       this.id = id;
    }
   
    public UserHasCountryId getId() {
        return this.id;
    }
    
    public void setId(UserHasCountryId id) {
        this.id = id;
    }




}


