package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * UserHasChannelId generated by hbm2java
 */
public class UserHasChannelId  implements java.io.Serializable {


     private int userId;
     private String channelCode;

    public UserHasChannelId() {
    }

    public UserHasChannelId(int userId, String channelCode) {
       this.userId = userId;
       this.channelCode = channelCode;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getChannelCode() {
        return this.channelCode;
    }
    
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserHasChannelId) ) return false;
		 UserHasChannelId castOther = ( UserHasChannelId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getChannelCode()==castOther.getChannelCode()) || ( this.getChannelCode()!=null && castOther.getChannelCode()!=null && this.getChannelCode().equals(castOther.getChannelCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getChannelCode() == null ? 0 : this.getChannelCode().hashCode() );
         return result;
   }   


}


