package com.iwtg.ipaymonitor.datalayer.model;
// Generated 11/04/2018 12:27:58 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String user;
     private String pass;
     private String name;
     private String lastName;
     private int admin;
     private boolean baja;
     private String motivo;

    public User() {
    }

    public User(String user, String pass, String name, String lastName, int admin, boolean baja, String motivo) {
       this.user = user;
       this.pass = pass;
       this.name = name;
       this.lastName = lastName;
       this.admin = admin;
       this.baja = baja;
       this.motivo = motivo;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public int getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(int admin) {
        this.admin = admin;
    }
    public boolean isBaja() {
        return this.baja;
    }
    
    public void setBaja(boolean baja) {
        this.baja = baja;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


